# Generated by Django 5.1.1 on 2024-11-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=20, max_digits=10),
            preserve_default=False,
        ),
    ]
